export const userBios = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac lectus felis.\nIn maximus lectus ante, non rutrum eros porttitor pulvinar. Proin pulvinar, ante vitae porta fermentum, elit ligula blandit neque, id vestibulum nisl justo ut neque. Donec convallis venenatis sapien sed mattis. Morbi iaculis dapibus leo.\nUt finibus tristique molestie. Donec in suscipit metus.",
  "Integer laoreet posuere velit, vitae convallis leo egestas ac.\nMaecenas eget urna tincidunt, mollis erat quis, elementum ex. Aliquam sit amet arcu mollis, tristique nisi ac, tincidunt nisl. Nulla in justo turpis.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
  "Sed a lectus mi. Curabitur tristique nunc sit amet porttitor vulputate. Praesent elementum gravida ligula vitae sagittis. Aliquam elit leo, bibendum sed posuere sed, dignissim at ligula. In quis lorem vel tortor posuere consequat.\nMorbi id est pulvinar ipsum luctus posuere quis sed nisl. Phasellus in tincidunt turpis. Integer non faucibus eros.",
  "Morbi feugiat magna in feugiat fringilla.\nSed accumsan augue eget semper ultrices. Phasellus convallis congue nisi ac rutrum. Donec ornare, quam sed pellentesque eleifend, urna neque luctus tellus, egestas volutpat lorem enim eu elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\nProin libero elit, ullamcorper ac lacus vitae, egestas accumsan leo.",
  "Donec eleifend suscipit augue, cursus rutrum augue placerat vel.\nNulla tortor tortor, hendrerit interdum massa vitae, tristique bibendum orci. Cras eget euismod eros. Quisque interdum ultricies sapien, vel porttitor enim eleifend quis.",
  "Integer at lectus at arcu rutrum molestie non non ligula. Quisque ac felis feugiat diam laoreet cursus.\nInteger scelerisque nunc nec laoreet blandit.",
  "Proin sollicitudin suscipit libero, sit amet fermentum mi facilisis a. Mauris aliquam non massa non pretium.\nCurabitur a ex maximus, imperdiet turpis feugiat, bibendum diam. Donec sagittis ligula id viverra sagittis.",
  "Vestibulum ultrices justo urna, nec dictum metus sagittis vitae.\nCras eget interdum odio. Nunc tristique diam vel diam suscipit fermentum. Curabitur risus ipsum, dictum id pharetra nec, congue a arcu. Curabitur quis ornare arcu.",
  "Ut volutpat magna vel iaculis consequat. Donec ut elementum neque. Curabitur dapibus urna ac massa scelerisque, a pharetra metus tincidunt. In arcu ipsum, feugiat et felis id, commodo consequat tortor.\nInteger egestas tortor non dolor iaculis, et laoreet lacus egestas. Donec egestas dapibus eros, a consectetur diam sodales et. Proin volutpat nisi ultricies mi facilisis sodales.",
  "Maecenas bibendum gravida ullamcorper. Nulla luctus justo eu orci imperdiet porta. Mauris quis metus sed nulla dapibus gravida. Mauris sit amet elit at arcu tincidunt volutpat tempor in leo.",
  "Proin tincidunt mollis tellus vel tempor. Pellentesque faucibus sapien ut nunc posuere scelerisque. Vestibulum est neque, elementum sit amet porttitor ac, mollis sit amet mauris.\nPraesent vestibulum felis vel vestibulum posuere.",
  "Nulla id maximus massa. Nam mi est, vestibulum et elit consectetur, luctus cursus eros.\nNulla facilisi. Donec faucibus tempus mi.\n\nCras ut velit eget purus tristique viverra. Nam porta risus odio, nec sollicitudin lacus imperdiet eget. Sed leo diam, fringilla in tortor eu, imperdiet vulputate mi. Etiam elementum fringilla turpis nec lacinia.",
  "Quisque sollicitudin, tellus at vehicula suscipit, metus magna consequat eros, vitae vulputate felis erat vel odio.\n\nCras posuere, elit ut semper ultricies, eros neque aliquet est, sed malesuada risus risus eu massa. Sed rutrum felis dignissim sem rhoncus maximus. Nulla porta gravida lectus hendrerit volutpat. Fusce ullamcorper interdum eros nec lacinia.\nDonec pretium, est eget venenatis hendrerit, dolor nunc finibus dolor, et mollis purus massa ut magna.",
  "In id purus id urna dapibus consectetur. Etiam eu ultricies ipsum. Cras venenatis fermentum ligula, eget maximus odio convallis eu. Donec quam lacus, egestas sed aliquam et, laoreet quis odio.\nDonec ac quam dignissim, blandit enim et, imperdiet tellus. Sed a leo non orci fermentum eleifend. Morbi quis cursus velit. Nunc mollis arcu eget ipsum condimentum ultricies.",
  "Ut congue lectus vitae imperdiet tincidunt. Donec consequat tristique lectus, vel gravida orci tristique nec. Interdum et malesuada fames ac ante ipsum primis in faucibus.\nDuis condimentum mi diam, sit amet sodales tortor eleifend ut. Proin dapibus risus ac diam lacinia semper.\n\nMorbi vel risus nec nunc condimentum consequat eget nec nunc.",
  "Nulla dapibus sodales libero, sit amet maximus ipsum dapibus nec.\nNunc luctus nunc viverra, varius dui eu, imperdiet ante. Morbi efficitur diam lorem, blandit sodales turpis condimentum nec. Donec bibendum eleifend metus, rutrum pharetra mi bibendum non. Aenean sit amet bibendum nulla.\nFusce dictum quis risus sit amet rhoncus.",
  "Integer egestas nec diam sit amet mattis. Nam maximus enim sit amet felis mattis, ac porttitor justo viverra. Aliquam a congue ligula, et commodo urna. Aliquam sed turpis ultrices, dictum magna id, volutpat arcu. Integer nec varius magna.",
  "Nulla facilisi. In faucibus vel lectus a consequat. Phasellus tortor sapien, laoreet quis elit quis, feugiat sagittis lorem.\n\nInteger finibus massa turpis, et varius massa congue ut.\nCurabitur iaculis sit amet nunc gravida vestibulum. Maecenas tempor at nisi vel vulputate. Sed et pretium lacus.",
  "Phasellus ut pretium mi. Duis velit odio, euismod non arcu quis, suscipit egestas augue. Aenean luctus est magna, quis pretium nisl porttitor eget. Duis tincidunt placerat nisi blandit gravida.\n\nDonec nulla eros, dictum ac tempus nec, malesuada eu diam. Nunc euismod at nibh nec sagittis. Sed id augue a justo dictum volutpat.",
  "Duis vitae est a orci sollicitudin pulvinar. Integer eget dictum odio. Duis in euismod est.\nMauris ullamcorper a sapien non volutpat. Nullam viverra, eros tempus varius vestibulum, velit sapien ultricies lectus, nec vehicula lacus nunc et risus.",
  "Cras sed nisl tincidunt odio ornare placerat. In ac dui sed neque suscipit malesuada. Pellentesque fermentum consectetur quam, in faucibus massa porttitor pulvinar.",
  "Etiam tempor urna sed dui euismod vestibulum. Integer ut ullamcorper ante. Nullam ultrices blandit urna, eget accumsan sapien lacinia in.",
  "Suspendisse sollicitudin mi sed orci aliquet, vel tempus libero finibus. Nam vitae viverra tortor. Curabitur sit amet velit vitae velit sodales condimentum. Etiam auctor accumsan augue eu volutpat. Aenean blandit mattis sapien id feugiat.",
  "Proin pellentesque urna orci, non mattis ante maximus eu. Aenean sit amet interdum quam. Fusce eros lorem, viverra non mi eget, tristique posuere ante.",
  "Proin ultricies id quam egestas convallis. Aenean sed arcu sit amet erat hendrerit mattis. Cras et leo sed libero congue porta. Duis lobortis convallis nisi viverra iaculis.\nNullam nec felis facilisis, vehicula mauris eu, aliquam arcu. Nunc facilisis sapien at ante tincidunt, eget eleifend odio eleifend.",
  "Nunc ante ipsum, commodo id vehicula a, congue et neque. Proin vestibulum erat sit amet leo tincidunt, non finibus diam mattis. Pellentesque tincidunt at nulla in eleifend.",
  "Aenean sed fringilla sapien, eu euismod tellus. Aliquam quis metus sit amet lorem fermentum tristique a ac nunc.\n\nPellentesque quis tempus mi, non semper elit. Nunc vel maximus ipsum. Nulla dolor neque, eleifend vel sollicitudin non, lacinia vitae nibh. In eleifend lorem laoreet, ultricies ex eu, elementum turpis.",
  "Nam vitae feugiat est. Pellentesque vitae ligula ac magna finibus maximus vel vel diam. Nulla ante elit, scelerisque ut sagittis vitae, ornare in erat.\nInteger felis mauris, luctus eget turpis sed, maximus luctus massa. Quisque aliquet pharetra accumsan. Duis viverra eleifend orci, sit amet fermentum mauris ultricies egestas. Pellentesque tincidunt quis metus ut consectetur.",
  "Nullam bibendum porta ex, in interdum diam venenatis mattis. Mauris sit amet ornare augue, a ultrices nisl. Praesent egestas nulla at dapibus vehicula. Mauris pretium lectus ac nunc condimentum consectetur.",
  "Etiam lacus nisl, ultrices ac rutrum nec, mollis non risus. Ut porta nunc sit amet est aliquam, ac gravida ex sodales. Sed tempor ullamcorper euismod. Cras in scelerisque massa, ut semper sapien. Sed ut leo nec nunc mattis venenatis ut sed ligula.",
];

export const getRandomBio = () => {
  const randomIndex = Math.floor(Math.random() * userBios.length);
  return userBios[randomIndex];
};
